import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "react-quill/dist/quill.snow.css";
import "@/styles/globals.css";
import "@/styles/ql.css";
import { cn } from "@/lib/utils";
import SideBar from "@/components/sidebar";
import Providers from "@/components/providers";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Admin Dashboard | LIKELION",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers>
          <div className="ml-[var(--sidebar-width)]">
            <SideBar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
